apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-demo-app
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Knative concurrency-based autoscaling (default).
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        # Target 10 requests in-flight per pod.
        autoscaling.knative.dev/target: "10"
        # Disable scale to zero with a minScale of 1.
        autoscaling.knative.dev/minScale: "0"
        # Limit scaling to max pods.
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: docker.io/bikramnehra/knative-demo-app
  traffic:
    - latestRevision: true
      percent: 100
    #- revisionName: knative-demo-app-5vcnr
    #  percent: 50
    #- revisionName: knative-demo-app-vlprt
    #  percent: 50